-- Gate 6 seed for RA weekly management project details.
-- Scope: public.ll_weekly_reports / public.ll_weekly_assets / public.ll_weekly_projects only.
-- This preserves source rows in row_json so the UI can move away from static JSON fallback.

do $$
declare
  v_report_id uuid := '00000000-0000-0000-0000-000000260427';
begin
  insert into public.ll_weekly_reports (
    id, week_key, organization, report_year, report_month, report_week,
    source_file_name, source_sha256, source_text, report_json
  ) values (
    v_report_id, '2026-04-5', '사업그룹4파트', 2026, 4, 5,
    'RA부문_사업그룹4파트_주간업무자료(안)_260427_취합.docx', 'fe542946536dee15dd7ae41f018e35b0c0dacb8b810d1d564e614b9be7fe441b', null,
    '{"sourceDocumentName":"RA부문_사업그룹4파트_주간업무자료(안)_260427_취합.docx","reportDate":"2026-04-06","summary":{"assetCount":20,"totalGrossAreaPy":537080,"riskAssetCount":5,"leaseUpIssueCount":6,"fullyLeasedCount":6},"seed":"gate6_weekly_project_details_seed"}'::jsonb
  )
  on conflict (week_key, organization) do update set
    source_file_name = excluded.source_file_name,
    source_sha256 = excluded.source_sha256,
    report_json = excluded.report_json,
    updated_at = now()
  returning id into v_report_id;

  delete from public.ll_weekly_assets where report_id = v_report_id;
  delete from public.ll_weekly_projects where report_id = v_report_id;

  insert into public.ll_weekly_assets (report_id, asset_code, asset_name, fund_code, fund_name, status, issue, plan, row_json)
  values
    (v_report_id, '', '아레나스안성', '', '', '', 'Lease-up', '', '{"id":"weekly_asset_01","no":1,"category":"개발/기설정","assetName":"아레나스안성","operationRisk":"","exitRisk":"","grossAreaPy":37656,"completion":"2024.05","investmentType":"개발","acquisition":"2024.05","loanMaturity":"","fundMaturity":"2028.05","costPerPy":"5.0","costTrend":"▼","coldRatio":"36%","occupancyRate":"44%","mainTenant":"하우져","mainIssue":"Lease-up","sourceRef":"TABLE 1 R2"}'::jsonb),
    (v_report_id, '', '여주본두리', '', '', '', 'Lease-up', '', '{"id":"weekly_asset_02","no":2,"category":"개발/기설정","assetName":"여주본두리","operationRisk":"","exitRisk":"","grossAreaPy":32904,"completion":"2023.11","investmentType":"개발","acquisition":"2023.11","loanMaturity":"","fundMaturity":"2028.10","costPerPy":"4.4","costTrend":"▼","coldRatio":"-","occupancyRate":"84%","mainTenant":"Maersk","mainIssue":"Lease-up","sourceRef":"TABLE 1 R3"}'::jsonb),
    (v_report_id, '', '화성석포리', '', '', '', 'Upside Potential 확보', '', '{"id":"weekly_asset_03","no":3,"category":"선매입","assetName":"화성석포리","operationRisk":"●","exitRisk":"●","grossAreaPy":32370,"completion":"2023.11","investmentType":"선매입","acquisition":"2022.02","loanMaturity":"2028.03","fundMaturity":"2028.03","costPerPy":"7.1","costTrend":"▲","coldRatio":"-","occupancyRate":"100%","mainTenant":"삼성전자로지텍","mainIssue":"Upside Potential 확보","sourceRef":"TABLE 1 R4"}'::jsonb),
    (v_report_id, '', '경산쿠팡물류', '', '', '', '재하도급업체 관련 대응', '', '{"id":"weekly_asset_04","no":4,"category":"실물","assetName":"경산쿠팡물류","operationRisk":"●","exitRisk":"●","grossAreaPy":29849,"completion":"2024.08","investmentType":"실물","acquisition":"2025.06","loanMaturity":"2028.06","fundMaturity":"2028.05","costPerPy":"5.7","costTrend":"→","coldRatio":"26%","occupancyRate":"100%","mainTenant":"쿠팡","mainIssue":"재하도급업체 관련 대응","sourceRef":"TABLE 1 R5"}'::jsonb),
    (v_report_id, '', '스카이박스1', '', '', '', '', '', '{"id":"weekly_asset_05","no":5,"category":"실물","assetName":"스카이박스1","operationRisk":"","exitRisk":"","grossAreaPy":10706,"completion":"2017.04","investmentType":"실물","acquisition":"2019.04","loanMaturity":"","fundMaturity":"2029.04","costPerPy":"","costTrend":"","coldRatio":"-","occupancyRate":"","mainTenant":"LG생활건강","mainIssue":"","sourceRef":"TABLE 1 R6"}'::jsonb),
    (v_report_id, '', '스카이박스2', '', '', '', 'Lease-up', '', '{"id":"weekly_asset_06","no":6,"category":"실물","assetName":"스카이박스2","operationRisk":"","exitRisk":"","grossAreaPy":15189,"completion":"2017.04","investmentType":"실물","acquisition":"2019.04","loanMaturity":"","fundMaturity":"2029.04","costPerPy":"5.5","costTrend":"▼","coldRatio":"-","occupancyRate":"80%","mainTenant":"쿠팡","mainIssue":"Lease-up","sourceRef":"TABLE 1 R7"}'::jsonb),
    (v_report_id, '', '이천동산', '', '', '', 'Upside Potential 확보', '', '{"id":"weekly_asset_07","no":7,"category":"실물","assetName":"이천동산","operationRisk":"","exitRisk":"","grossAreaPy":16740,"completion":"2015.11","investmentType":"실물","acquisition":"2021.03","loanMaturity":"","fundMaturity":"2031.03","costPerPy":"6.4","costTrend":"→","coldRatio":"-","occupancyRate":"99%","mainTenant":"쿠팡","mainIssue":"Upside Potential 확보","sourceRef":"TABLE 1 R8"}'::jsonb),
    (v_report_id, '', '에이블로지스', '', '', '', '', '', '{"id":"weekly_asset_08","no":8,"category":"실물","assetName":"에이블로지스","operationRisk":"","exitRisk":"","grossAreaPy":9069,"completion":"2016.11","investmentType":"실물","acquisition":"2021.03","loanMaturity":"","fundMaturity":"2031.03","costPerPy":"","costTrend":"","coldRatio":"-","occupancyRate":"","mainTenant":"아워박스","mainIssue":"","sourceRef":"TABLE 1 R9"}'::jsonb),
    (v_report_id, '', '부국물류', '', '', '', '', '', '{"id":"weekly_asset_09","no":9,"category":"실물","assetName":"부국물류","operationRisk":"","exitRisk":"","grossAreaPy":5658,"completion":"2016.06","investmentType":"실물","acquisition":"2021.03","loanMaturity":"","fundMaturity":"2031.03","costPerPy":"","costTrend":"","coldRatio":"-","occupancyRate":"","mainTenant":"한익스프레스","mainIssue":"","sourceRef":"TABLE 1 R10"}'::jsonb),
    (v_report_id, '', '창원두동LG', '', '', '', 'ML임차인 Re-tenanting', '', '{"id":"weekly_asset_10","no":10,"category":"실물","assetName":"창원두동LG","operationRisk":"","exitRisk":"","grossAreaPy":16506,"completion":"2019.11","investmentType":"실물","acquisition":"2023.02","loanMaturity":"","fundMaturity":"2028.02","costPerPy":"7.0","costTrend":"▲","coldRatio":"-","occupancyRate":"100%","mainTenant":"LG전자","mainIssue":"ML임차인 Re-tenanting","sourceRef":"TABLE 1 R11"}'::jsonb),
    (v_report_id, '', '이천회억리', '', '', '', 'Lease-up, Refinancing', '', '{"id":"weekly_asset_11","no":11,"category":"선매입","assetName":"이천회억리","operationRisk":"●","exitRisk":"●","grossAreaPy":13531,"completion":"2023.11","investmentType":"선매입","acquisition":"2025.01","loanMaturity":"2027.01","fundMaturity":"2028.01","costPerPy":"6.4","costTrend":"▲","coldRatio":"25%","occupancyRate":"73%","mainTenant":"한국로지스풀","mainIssue":"Lease-up, Refinancing","sourceRef":"TABLE 1 R12"}'::jsonb),
    (v_report_id, '', '부산송정', '', '', '', 'EOD, 소송, 신규개발(DC)', '', '{"id":"weekly_asset_12","no":12,"category":"실물","assetName":"부산송정","operationRisk":"●","exitRisk":"●","grossAreaPy":7377,"completion":"2015.11","investmentType":"실물","acquisition":"2017.01","loanMaturity":"2024.03","fundMaturity":"2047.01","costPerPy":"9.1","costTrend":"▲","coldRatio":"100%","occupancyRate":"공실","mainTenant":"-","mainIssue":"EOD, 소송, 신규개발(DC)","sourceRef":"TABLE 1 R13"}'::jsonb),
    (v_report_id, '', '안성성은리', '', '', '', 'Lease-up, 투자자확보(위약 50억)', '', '{"id":"weekly_asset_13","no":13,"category":"선매입","assetName":"안성성은리","operationRisk":"","exitRisk":"","grossAreaPy":34285,"completion":"2024.12","investmentType":"선매입","acquisition":"선매입(연장)","loanMaturity":"","fundMaturity":"연장중","costPerPy":"7.0","costTrend":"▲","coldRatio":"17%","occupancyRate":"60%","mainTenant":"일본통운","mainIssue":"Lease-up, 투자자확보(위약 50억)","sourceRef":"TABLE 1 R14"}'::jsonb),
    (v_report_id, '', '경남양산석암', '', '', '', 'Lease-up, 투자자확보(위약 68억)', '', '{"id":"weekly_asset_14","no":14,"category":"선매입","assetName":"경남양산석암","operationRisk":"","exitRisk":"","grossAreaPy":15953,"completion":"2024.07","investmentType":"선매입","acquisition":"선매입(연장)","loanMaturity":"","fundMaturity":"연장중","costPerPy":"7.5","costTrend":"▲","coldRatio":"25%","occupancyRate":"20%","mainTenant":"소셜빈","mainIssue":"Lease-up, 투자자확보(위약 68억)","sourceRef":"TABLE 1 R15"}'::jsonb),
    (v_report_id, '', '야탑쿠팡물류', '', '', '', '쿠팡 M/L(예정) 및 출자', '', '{"id":"weekly_asset_15","no":15,"category":"개발","assetName":"야탑쿠팡물류","operationRisk":"","exitRisk":"","grossAreaPy":21340,"completion":"2023.10","investmentType":"개발","acquisition":"개발","loanMaturity":"","fundMaturity":"2027.08","costPerPy":"10.4","costTrend":"→","coldRatio":"47%","occupancyRate":"개발","mainTenant":"쿠팡","mainIssue":"쿠팡 M/L(예정) 및 출자","sourceRef":"TABLE 1 R16"}'::jsonb),
    (v_report_id, '', '포천정교리', '', '', '', '쿠팡 M/L(예정) 및 출자', '', '{"id":"weekly_asset_16","no":16,"category":"개발","assetName":"포천정교리","operationRisk":"","exitRisk":"","grossAreaPy":16313,"completion":"개발","investmentType":"개발","acquisition":"개발","loanMaturity":"","fundMaturity":"2030.02","costPerPy":"7.1","costTrend":"→","coldRatio":"51%","occupancyRate":"개발","mainTenant":"쿠팡","mainIssue":"쿠팡 M/L(예정) 및 출자","sourceRef":"TABLE 1 R17"}'::jsonb),
    (v_report_id, '', '아레나스양지', '', '', '', '임대료정상화(88%/GLA)', '', '{"id":"weekly_asset_17","no":17,"category":"2nd 블펀","assetName":"아레나스양지","operationRisk":"","exitRisk":"","grossAreaPy":105791,"completion":"","investmentType":"선매입","acquisition":"2019.03","loanMaturity":"","fundMaturity":"2027.05","costPerPy":"3.8","costTrend":"▼","coldRatio":"-","occupancyRate":"99%","mainTenant":"CJ/용마로지스","mainIssue":"임대료정상화(88%/GLA)","sourceRef":"TABLE 1 R18"}'::jsonb),
    (v_report_id, '', '인천석남물류', '', '', '', 'Upside Potential 확보', '', '{"id":"weekly_asset_18","no":18,"category":"실물","assetName":"인천석남물류","operationRisk":"●","exitRisk":"●","grossAreaPy":90540,"completion":"2023.08","investmentType":"실물","acquisition":"2023.01","loanMaturity":"2027.04","fundMaturity":"2033.07","costPerPy":"6.8","costTrend":"→","coldRatio":"14%","occupancyRate":"100%","mainTenant":"쿠팡","mainIssue":"Upside Potential 확보","sourceRef":"TABLE 1 R19"}'::jsonb),
    (v_report_id, '', '평택아디다스', '', '', '', '소송대응/Re-tenanting/복원공사', '', '{"id":"weekly_asset_19","no":19,"category":"실물","assetName":"평택아디다스","operationRisk":"","exitRisk":"","grossAreaPy":15374,"completion":"","investmentType":"실물","acquisition":"2021.10","loanMaturity":"","fundMaturity":"2032.08","costPerPy":"8.9","costTrend":"▲","coldRatio":"-","occupancyRate":"100%","mainTenant":"아디다스","mainIssue":"소송대응/Re-tenanting/복원공사","sourceRef":"TABLE 1 R20"}'::jsonb),
    (v_report_id, '', '안성홈플러스', '', '', '', 'ML임차인 Re-tenanting', '', '{"id":"weekly_asset_20","no":20,"category":"실물","assetName":"안성홈플러스","operationRisk":"","exitRisk":"","grossAreaPy":9929,"completion":"","investmentType":"실물","acquisition":"2022.08","loanMaturity":"","fundMaturity":"2032.07","costPerPy":"17.7(유휴부지별도)","costTrend":"▲","coldRatio":"100%","occupancyRate":"100%","mainTenant":"홈플러스","mainIssue":"ML임차인 Re-tenanting","sourceRef":"TABLE 1 R21"}'::jsonb);

  insert into public.ll_weekly_projects (report_id, project_type, project_name, stakeholder, status, issue, plan, row_json)
  values
    (v_report_id, 'managementProjects', '이천 회억리 물류센터', '운용/Exit ●', '임대: 초록마을/정육각 기업회생절차 개시 및 명도 완료, 한진 B2층(저온) 전체 입주개시. 담보대출: 27년 1월 만기, 기존 대주단 미연장 의사. 매각: 우선주 수익률 IRR 18.0% 기준으로 매각가가 시차별로 높아짐.', '지상1층(GLA 27%) 임대차 마케팅 진행중 / 기존 대주단 미연장에 따른 Refinancing 대응 / IRR 기준 변경 가능성 타진 필요', '지상1층 임대차 마케팅 / 5월 중 대주단 미팅 / 시장 현황 설명으로 IRR 18.0% 기준 변경 가능성 타진 / Share-deal 또는 Asset-deal 관련없이 잠재매수의향자 tapping 예정', '{"id":"weekly_mgmt_01","no":1,"risk":"운용/Exit ●","projectName":"이천 회억리 물류센터","detailRows":[{"label":"주소","value":"이천 마장면 회억리 105"},{"label":"섹터","value":"복합물류"},{"label":"투자 전략","value":"선매입 / Vehicle 펀드 / 펀드설정 25.01 / 펀드만기 28.01"},{"label":"연면적","value":"13,531평"},{"label":"대지면적","value":"8,986평"},{"label":"용적률 및 건폐율","value":""},{"label":"규모(층수)","value":"지상3층"},{"label":"총 사업비","value":"938억"},{"label":"Equity","value":"445억 / 우선주 380억 / 보통주 65억"},{"label":"Loan","value":"465억 / 선순위 465억 / LTV 54.7% / All-in 5.5%"},{"label":"기타","value":"매입가 800억(평당 5.9백만) / 취득원가 862억(평당 6.4백만) / 장부가 897억(평당 6.6백만) / 목표매각가 1,132억(평당 8.4백만) / 임차면적 13,531평 / 임대율 73% / 임대구조 멀티Tenant / 저온비중 25% / 주임차사 한국로지스풀 / WALE 2.7년 / 시공사 까뮤이앤씨 / 구조 PC+RC / 접안유형 자연접안 / 전기용량 2,200kW / 하중 저온 2.5T, 상온 2.0T / 주요투자자 Oaktree, GS retail, GF logis, IGIS 등 / 주요대주 신협11지점, BNK, 신한 / 대출만기 27.01 / 운용보수 연2.4억 / 매입보수 6.8억 / 매각보수 2.3억 / 성과보수 매각차익 2.0%, 8.4억"}],"overview":"복합물류, 선매입, 이천 마장면 회억리 105, 지상 3층, 연면적 13,531평, 임대율 73%, 주임차사 한국로지스풀.","investment":"취득원가 862억원, 장부가 897억원, 목표매각가 1,132억원, Loan 465억원, LTV 54.7%.","status":"임대: 초록마을/정육각 기업회생절차 개시 및 명도 완료, 한진 B2층(저온) 전체 입주개시. 담보대출: 27년 1월 만기, 기존 대주단 미연장 의사. 매각: 우선주 수익률 IRR 18.0% 기준으로 매각가가 시차별로 높아짐.","issue":"지상1층(GLA 27%) 임대차 마케팅 진행중 / 기존 대주단 미연장에 따른 Refinancing 대응 / IRR 기준 변경 가능성 타진 필요","plan":"지상1층 임대차 마케팅 / 5월 중 대주단 미팅 / 시장 현황 설명으로 IRR 18.0% 기준 변경 가능성 타진 / Share-deal 또는 Asset-deal 관련없이 잠재매수의향자 tapping 예정","sourceRef":"TABLE 3 R2"}'::jsonb),
    (v_report_id, 'managementProjects', '화성 석포리 물류센터', '운용/Exit ●', '담보대출 Tr.B 셀다운 검토(w/LFC), 기존 대주 진행현황 안내 및 F/u, Tr.B 신한캐피탈 대출수수료 지급 예정(5월 초), 신규 검토 대주 대응. 사면 보강공사 완료에 따른 개발행위 준공검사 신청. 전기차 충전시설 설치 신고 및 보험 가입 검토.', '담보대출 Tr.B 셀다운 / 일부 토지 매각 관련 협의 / 전기차 충전시설 설치 신고 및 보험가입 의무화 대응 / 태양광 임대차계약 관련 발전시설 설치 절차 / 삼성전자로지텍 시설물 분리운영 / 하자 처리', 'Tr.B 셀다운 검토 지속 / 일부 토지 매각 관련 Tr.B 셀다운 처 확정 시 북부종합건설 협의 / 준공검사 승인 후 공작물축조신고서 제출 예정 / 전기차 충전시설 보험 가입 검토 / 태양광 개발행위허가와 한전 계약 등 후속 절차 / 시설물 분리운영 검토 / SGC이테크 하자 처리', '{"id":"weekly_mgmt_02","no":2,"risk":"운용/Exit ●","projectName":"화성 석포리 물류센터","detailRows":[{"label":"주소","value":"화성시 장안면 석포리 147-12"},{"label":"섹터","value":"상온물류"},{"label":"투자 전략","value":"선매입 / Vehicle 펀드 / 펀드설정 22.02 / 펀드만기 28.03"},{"label":"연면적","value":"32,370평"},{"label":"대지면적","value":"25,888평"},{"label":"용적률 및 건폐율","value":""},{"label":"규모(층수)","value":"B2/3F, B2/2F"},{"label":"총 사업비","value":"2,379억"},{"label":"Equity","value":"615억 / 우선주(1종) 250억 / 보통주(2종) 245억 / 보통주(3종) 40억"},{"label":"Loan","value":"1,695억 / 선순위 1,500억 / 중순위 195억 / LTV 73% / All-in 5.5%, TBD"},{"label":"기타","value":"매입가 2,120억(평당 655만) / 취득원가 2,301억(평당 711만) / 장부가 2,413억(평당 745만) / 목표매각가 2,363억(평당 730만) / 임대면적 32,370평 / 임대율 100% / 임대구조 싱글 tenant / 저온비중 0% / 주임차사 삼성전자로지텍 / WALE 2.86 / 시공사 SGC이테크 / 구조 합성·철근철골콘크리트구조 / 접안유형 자연접안 / 전기용량 3,500kW / 하중 2.5T / 주요투자자 메트라이프, 이지스, 성담, BNK캐피탈 등 / 주요대주 삼성SRA, 메트라이프, 신한캐피탈 등 / 대출만기 28.03 / 매입보수 12억 / 운용보수 설정액 연 0.40% / 매각보수 매각가 0.5%, TBD"}],"status":"담보대출 Tr.B 셀다운 검토(w/LFC), 기존 대주 진행현황 안내 및 F/u, Tr.B 신한캐피탈 대출수수료 지급 예정(5월 초), 신규 검토 대주 대응. 사면 보강공사 완료에 따른 개발행위 준공검사 신청. 전기차 충전시설 설치 신고 및 보험 가입 검토.","issue":"담보대출 Tr.B 셀다운 / 일부 토지 매각 관련 협의 / 전기차 충전시설 설치 신고 및 보험가입 의무화 대응 / 태양광 임대차계약 관련 발전시설 설치 절차 / 삼성전자로지텍 시설물 분리운영 / 하자 처리","plan":"Tr.B 셀다운 검토 지속 / 일부 토지 매각 관련 Tr.B 셀다운 처 확정 시 북부종합건설 협의 / 준공검사 승인 후 공작물축조신고서 제출 예정 / 전기차 충전시설 보험 가입 검토 / 태양광 개발행위허가와 한전 계약 등 후속 절차 / 시설물 분리운영 검토 / SGC이테크 하자 처리","sourceRef":"TABLE 3 R3"}'::jsonb),
    (v_report_id, 'managementProjects', '부산 송정 물류센터', '운용/Exit ●', 'EOD 발생으로 법원 경매 진행 중: EOD 발생(23.12.08), 경매 개시(24.03.04), 1차 매각기일 유찰(25.06.04/700억), 2차 매각기일 채권자 협의를 통한 연기 신청(최저매각가 490억). 하나로TNS 손해배상 청구소송 진행. DC Conversion 검토 협조. 집합투자재산 공정가치 평가 진행.', 'EOD 및 경매 대응 / 후순위 대주 대응 / 하나로TNS 손해배상 청구소송 / 감정인 의견 대응 / DC Conversion 검토', '경매 대응 방안 검토 및 협의 / 하나로TNS 소송 대응 / DC Conversion 검토 협조', '{"id":"weekly_mgmt_03","no":3,"risk":"운용/Exit ●","projectName":"부산 송정 물류센터","detailRows":[{"label":"주소","value":"부산 강서구 송정동 1715-2"},{"label":"섹터","value":"저온물류"},{"label":"투자 전략","value":"실물 / Vehicle 펀드 / 펀드설정 17.01 / 펀드만기 47.01"},{"label":"연면적","value":"7,377평"},{"label":"대지면적","value":"3,427평"},{"label":"용적률 및 건폐율","value":""},{"label":"규모(층수)","value":"B1/6F"},{"label":"총 사업비","value":"938억"},{"label":"Equity","value":"280억"},{"label":"Loan","value":"480억 / 선순위 400억 / 중순위 80억 / LTV 59.4% / All-in 6.0%, 9.0%"},{"label":"기타","value":"매입가 623억(평당 844만) / 취득원가 668억(평당 905만) / 장부가 808억(평당 1,095만) / 목표매각가 - / 임대면적 7,377평 / 임대율 0%(전체공실) / 임대구조 - / 저온비중 100% / 주임차사 - / WALE - / 시공사 신세계건설 / 구조 PC, 철골, RC / 전기용량 2,500kW / 주요투자자 안젤로고든 / 주요대주 유암코, 대신저축, 스카이저축 / 대출만기 24.03(EOD) / 목표 IRR(CG 포함) 30.29%, CG 미포함 10.26% / 매입보수 12.46억 / 운용보수 자산총액 연 0.80%, 연 6.5억 / 매각보수 매각가 1.0%, TBD"}],"status":"EOD 발생으로 법원 경매 진행 중: EOD 발생(23.12.08), 경매 개시(24.03.04), 1차 매각기일 유찰(25.06.04/700억), 2차 매각기일 채권자 협의를 통한 연기 신청(최저매각가 490억). 하나로TNS 손해배상 청구소송 진행. DC Conversion 검토 협조. 집합투자재산 공정가치 평가 진행.","issue":"EOD 및 경매 대응 / 후순위 대주 대응 / 하나로TNS 손해배상 청구소송 / 감정인 의견 대응 / DC Conversion 검토","plan":"경매 대응 방안 검토 및 협의 / 하나로TNS 소송 대응 / DC Conversion 검토 협조","sourceRef":"TABLE 3 R4"}'::jsonb),
    (v_report_id, 'managementProjects', '경산 쿠팡 물류센터', '운용/Exit ●', '하도급 업체 유치권 주장 / 투자구조 변경(자산거래NPL 구조), 이지스 AI팀(NPL)과 협업 / 담보대출 대주 심의완료 / 6월 27일 클로징 완료 / 재하도급 업체(효현건설) 시위 / 공정위 회신 완료 및 소장 접수 완료 / 쿠팡 운용중(상온, 저온) / 9층 화재(25.12.16) 치유 완료 / 천장 사고처리 완료 / 경산산업단지 입주계약 체결 완료', '재하도급 업체 유치권 주장 및 시위 관련 대응', '25.06 체결한 하자치유 및 유치권 포기에 대한 합의서에 근거하여 대응 예정', '{"id":"weekly_mgmt_04","no":4,"risk":"운용/Exit ●","projectName":"경산 쿠팡 물류센터","detailRows":[{"label":"주소","value":"경북 경산시 진량읍 문천리 903"},{"label":"섹터","value":"복합물류"},{"label":"투자 전략","value":"실물매입 / Vehicle 펀드 / 펀드설정 25.05 / 펀드만기 28.05"},{"label":"연면적","value":"29,849평"},{"label":"대지면적","value":"5,389평"},{"label":"용적률 및 건폐율","value":""},{"label":"규모(층수)","value":"B2/12F"},{"label":"총 사업비","value":"1,835억"},{"label":"Equity","value":"535억 / 우선주 350억 / 보통주 185억"},{"label":"Loan","value":"1,300억 / 선순위 1,000억 / 중순위 300억 / LTV 64.4% / All-in 5.5%, 6.5%"},{"label":"기타","value":"매입가 1,558억(평당 5.2백만) / 취득원가 1,698억(평당 5.7백만) / 장부가 2,020억(평당 6.8백만) / 목표매각가 2,140억(평당 7.2백만) / 임차면적 23,061평 / 보증금 57억 / 임대율 100% / 임대구조 싱글Tenant / 저온비중 26% / 주임차사 쿠팡 / WALE 4.0년 / 시공사 삼부토건 / 구조 PC+RC / 접안유형 램프접안 / 전기용량 9,000kW / 하중 저온 2.2~2.5T, 상온 2.0T / 주요투자자 경산SS1호(NPL4호펀드), 경산로지스1-1호(NH증권) / 주요대주 한투캐피탈, 미래캐피탈, 수협은행, IM캐피탈, 광주은행 / 대출만기 28.06 / 목표IRR 우선주 22.6%, 보통주 26.5% / 매입보수 13.15억 / 운용보수 설정액 535억 연0.51%, 보통주 재간접 설정액 181억 연0.05%, 우선주 재간접 설정액 350억 연0.05%, 연2.96억 / 성과보수 우선주IRR 15%, 보통주IRR 20%, 초과수익의 20%, TBD"}],"status":"하도급 업체 유치권 주장 / 투자구조 변경(자산거래NPL 구조), 이지스 AI팀(NPL)과 협업 / 담보대출 대주 심의완료 / 6월 27일 클로징 완료 / 재하도급 업체(효현건설) 시위 / 공정위 회신 완료 및 소장 접수 완료 / 쿠팡 운용중(상온, 저온) / 9층 화재(25.12.16) 치유 완료 / 천장 사고처리 완료 / 경산산업단지 입주계약 체결 완료","issue":"재하도급 업체 유치권 주장 및 시위 관련 대응","plan":"25.06 체결한 하자치유 및 유치권 포기에 대한 합의서에 근거하여 대응 예정","sourceRef":"TABLE 3 R5"}'::jsonb),
    (v_report_id, 'managementProjects', '인천 석남 물류센터', '운용/Exit ●', '(24.04) 거래종결 완료 / (24.05) 매도자(쿠거)-시공사(동원건설산업) 간 합의서 체결 및 시공사 유치권 포기각서 제출 / (25.02) KKR 지분(인컴 2-4-4호) 매각 완료 / (25.05) 이지스 보통주 투자액 50억원 매각완료', '', '', '{"id":"weekly_mgmt_05","no":5,"risk":"운용/Exit ●","projectName":"인천 석남 물류센터","detailRows":[{"label":"주소","value":"인천 서구 석남동 224-20"},{"label":"섹터","value":"복합물류"},{"label":"투자 전략","value":"선매입 / Vehicle 펀드 / 펀드설정 22.12 / 펀드만기 33.07"},{"label":"연면적","value":"90,541평"},{"label":"대지면적","value":"16,393평"},{"label":"용적률 및 건폐율","value":""},{"label":"규모(층수)","value":"B1/8F"},{"label":"총 사업비","value":"6,355억"},{"label":"Equity","value":"2,396억 / 보통주 2,396억"},{"label":"Loan","value":"3,426억 / 선순위 3,426억 / LTV 54.0% / All-in 6.1%(선취1.0%, CD+2.2%)"},{"label":"기타","value":"매입가 5,850억(평당 6.5백만) / 취득원가 5,935억(평당 6.6백만) / 장부가 6,340억(평당 7.0백만) / 목표매각가 7,536억(평당 8.3백만) / 임차면적 90,522평 / 보증금 83억 / 임대율 100% / 임대구조 마스터리스 / 저온비중 14% / 주임차사 쿠팡 / WALE 8.1년 / 시공사 동원건설산업 / 구조 PC+RC / 접안유형 램프접안 / 전기용량 13,950kW / 하중 저온 2.5T, 상온 2.0T / 주요투자자 인컴앤그로스2호(NPS 등), 장기지분형1-1호(KTCU 등), 인컴앤그로스2-4-4호(KBIZ) / 주요대주 KDB, DB손보, 하나, 신한, 현대해상, 전북은행 / 대출만기 27.04 / 운용보수 자1 설정액 729억 연0.77%, 자3 설정액 1,200억 연0.72%, 자4 설정액 467억 연0.02%, 연14.5억 / 매입보수 17.2억 / 매각보수 35.8억 / 성과보수 자1 IRR 8.0%, 자3 IRR 6.0%, 자4 IRR 8.0%, 초과수익의 15%, TBD"}],"overview":"복합물류, 선매입, 인천 서구 석남동 224-20, B1/8F, 연면적 90,541평, 임대율 100%, 주임차사 쿠팡.","investment":"취득원가 5,935억원, 장부가 6,340억원, 목표매각가 7,536억원, Loan 3,426억원, LTV 54.0%.","status":"(24.04) 거래종결 완료 / (24.05) 매도자(쿠거)-시공사(동원건설산업) 간 합의서 체결 및 시공사 유치권 포기각서 제출 / (25.02) KKR 지분(인컴 2-4-4호) 매각 완료 / (25.05) 이지스 보통주 투자액 50억원 매각완료","issue":"","plan":"","sourceRef":"TABLE 3 R6"}'::jsonb);
end $$;
